### ISSUE TITLE
Set Up NMP-ARM

### ISSUE THREAD

**Issue by LolandaE** [bcgov/agri-nmp#560]
**Describe the task**
Developers have NMP set up locally.

**Acceptance Criteria**
- [ ] Set up front end
- [ ] Set up back end
- [ ] Test digital service (aka app) locally

**Additional context**
N/A

**Comment by norrisng-bc** [comment]
NMP appears to use Source-to-Image (s2i) for building. OpenShift templates are provided in [`agri-nmp/OpenShift`](https://github.com/bcgov/agri-nmp/tree/master/OpenShift), presumably for this purpose. The problem, however, is that it's missing files needed by s2i.

While it does have an [`assemble`](https://github.com/bcgov/agri-nmp/blob/master/app/.s2i/bin/assemble) file (equired by s2i), it doesn't have a `Dockerfile` (also required by s2i) or a `docker-compose.yaml` (which Docker can use directly to build a container locally).

It has a [`Dockerfile.rhel7`](https://github.com/bcgov/agri-nmp/blob/master/OpenShift/s2i-dotnetcore-node/Dockerfile.rhel7), but it doesn't provide a PostgreSQL database, which NMP uses.


*More reading on s2i:*
https://dzone.com/articles/how-to-create-a-builder-image-with-s2i
https://opensource.com/article/19/5/source-image-golang-part-1

**Comment by norrisng-bc** [comment]
_Update_: there doesn't seem to be an obvious way to run this locally.
*  As mentioned above, there are no Dockerfiles or `docker-compose.yaml`, so we can't build a container or use `s2i`.
* The templates in [`agri-nmp/OpenShift`](https://github.com/bcgov/agri-nmp/tree/master/OpenShift) are OpenShift-specific and can't be used in Kubernetes (OpenShift isn't local, but k8s is, so it would've been a way to use them locally).
* Running the components individually (i.e. `dotnet run` + `postgres -D`) doesn't work, as it requires a bunch of environment variables, and there's no script/schema with which to create a PostgreSQL database from scratch

Conor has said that he'll investigate this further.
