### ISSUE TITLE
Fix NMP Certificate

### ISSUE THREAD

**Issue by LolandaE** [bcgov/agri-nmp#563]
**Describe the Bug**
When a user attempts to access https://nmp.apps.nrs.gov.bc.ca, it results in a security warning, as the certificate being served is for https://www.nmp.apps.nrs.gov.bc.ca (the mismatch is the error).

**Expected Behaviour**
Users access the NMP site without security warning

**Actual Behaviour**
Users are getting a "your connection is not private" message when accessing the NMP

**Implications**
This is confusing for the user and they may stop using the app and apply fertilizer incorrectly.
Forces the user to bypass security settings which they not know how to do - not a best practice

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://nmp.apps.nrs.gov.bc.ca/'
2. See "your connection is not private" security warning

**Comment by norrisng-bc** [comment]
**Update:** it is indeed automated, but there is a misconfiguration somewhere such that it doesn't work correctly.

It renews on Aug 5, and requests a certificate (valid for a year) for: 
* https://www.nmp.apps.nrs.gov.bc.ca 
* https://nmp.apps.nrs.gov.bc.ca

Attempting to access https://nmp.apps.nrs.gov.bc.ca results in security errors, as the certificate being served is for https://www.nmp.apps.nrs.gov.bc.ca (the mismatch is the error). 

However, attempting to directly access https://www.nmp.apps.nrs.gov.bc.ca results in a 404.

The fix would require fixing the configuration, such that NMP (`nmp-web`) serves the correct matching certificate alongside the web app.

In the meantime, the platform link (https://agri-nmp.apps.silver.devops.gov.bc.ca) can be used as a temporary workaround. However, the OCP wildcard certificate (which this link uses, and so does nmp-msa and nmp-arm in their current form) is [not meant for production workloads](https://developer.gov.bc.ca/BC-Government-OpenShift-DevOps-Security-Considerations#tls-certificates), so those apps may need to be served from a dedicated subdomain in the future.

**Comment by norrisng-bc** [comment]
**Update:** route patched with old certificate for now (it expires on Sep 3). Everything will work normally till then.

The initial certificate renewal approvals lapsed on Aug 19, so we'll have to go through the ServiceDesk approval process once again. 

I've wiped/reinstalled Certbot; this will make it generate a new certificate signing request, and Entrust will send emails with the tracking IDs to the current service owner (which can then be used in the subsequent ServiceDesk ticket).

Once it's approved (the service owner will receive an email notification from Entrust), when Certbot runs again (either manually-triggered or scheduled cronjob), it _should_ grab the correct cert and install it.

To run the cronjob manually:
```
oc create job -n $NAMESPACE "certbot-manual-$(date +%s)" --from=cronjob/certbot
```
(replace `$NAMESPACE` with the name of the corresponding OpenShift Prod namespace)

Logs aren't saved forever, so it might be a good idea to download the log from the pod associated with the cronjob run.
