### ISSUE TITLE
NMP Cert Expiry September 3rd (Let's Encrypt)

### ISSUE THREAD

**Issue by jakemorr** [bcgov/agri-nmp#582]
**Describe the task**
Certificate expires September 3rd, 2023. There should be an email reminder in the team mailbox on August 3rd, 2023. Before this date, update NMP with Let's Encrypt temporary cert.

**Purpose**
This is required so that the end user doesn't experience a "your connection is not private" warning message (even though they can still click through and use the application).

**Acceptance Criteria**
- [ ] Certificate is renewed and end user arrives at homepage with no warning message displayed

**Additional Context**
- CERTBOT_SERVER parameter will need to be updated to: https://acme-v02.api.letsencrypt.org/directory and run certbot after config change
- Add'l documentation with commands to run: https://github.com/BCDevOps/certbot/blob/master/docker/README.md
- Need to look into why it doesn't send notifications to the Sustainment Team inbox about renewals, etc.
- Did SO or someone in NMP receive it?

**Comment by LolandaE** [comment]
Let's Encrypt cert set up to expire November 18
