### ISSUE TITLE
NMP Validation/Clean-up Farm information page

### ISSUE THREAD

**Issue by jakemorr** [bcgov/agri-nmp#597]
**As a** *Farmer using the calculator* **I want** *a clear workflow that guide me through the calculator* **So That** *I don't cause it to crash, and ensure all the information is entered*

**Additional Context**
- only field on Farm Information that needs validation is the Farm Name field
- the rest already has validation
- Red text under the field that needs to be filled in is the standard for our validation

**Acceptance Criteria**
- [x] Given I have entered a farm name, When I click Next, Then I Move to the next page
- [x] Given I have not entered a farm name, When I click Next, Then red text notifies me that i need to enter a farm name before proceeding

**Comment by joandrews** [comment]
@dmitri-korin-bcps Tested. Everything looks good.
