### ISSUE TITLE
NMP Validation/Clean-up Fields List page

### ISSUE THREAD

**Issue by jakemorr** [bcgov/agri-nmp#598]
**As a** *Farmer using the calculator* **I want** *a clear workflow that guides me through the calculator* **So That** *I don't cause it to crash, and ensure all the information is entered without jumping back page to page*

**Additional Context**
- this tab shows up first when you select yes to horticultural crops
- Red text under the field that needs to be filled in is the standard for our validation

**Acceptance Criteria**
- [x] Given I am on the Fields and Soil Tab and the Fields List Sub tab, When I click Next without adding a field, Then red text notifies me that I need to click add a field to proceed. 
- [x] Given I am on the Fields and Soil Tab and the Fields List Sub tab, When I click Next after adding a field, Then I Proceed to the Soil Tests Sub Tab

**Comment by joandrews** [comment]
@dmitri-korin-bcps Everything looks good. If a field is not added on the Field List page, can the red text read 'You must add a field to proceed'?
