### ISSUE TITLE
Update NMP Information.docx file in 'Dev Chat'

### ISSUE THREAD

**Issue by LocalNewsTV** [bcgov/agri-nmp#619]
**Describe the task**
Update "NMP Information.docx" Document in 'Dev Chat' 

**Purpose**
Not all information and tips need to be documented in a public facing repo. But with developers cycling through Sustainment team its valuable to keep this information for the next generation of developers to consume when working in these spaces

**Acceptance Criteria**
- [x] Information Cleaned up, Updated and Added to in Document
- [x] Headers used appropriately
- [x] Table of contents added

**Additional context**
- You can add tips involving setups, weird nuances, or advice if future tickets may impact an area you worked on
- GWELLS currently has a pretty up to date one, for reference

**Comment by fergmac** [comment]
@acatchpole https://bcgov.sharepoint.com/:w:/r/teams/05196-DevChat/Shared%20Documents/Dev%20Chat/NMP-MSA-ARM/NMP%20Information.docx?d=w85239c87c679470fa5191ae1ddb9dfca&csf=1&web=1&e=M2Nqkb
