### ISSUE TITLE
Add berry fertilizers to static data

### ISSUE THREAD

**Issue by joandrews** [bcgov/agri-nmp#628]
**As a** *user* **I want** *berry fertilizers added to the list of dry and dry fertilizers* **So That** *I can easily determine the amount of fertilizer I need to apply*

[Berry fertilizers.xlsx](https://github.com/bcgov/agri-nmp/files/14426065/Berry.fertilizers.xlsx)

**Acceptance Criteria**
- [x] Add the following list of fertilizers to static data, so users can select them when they click the 'Add fertilizer' button on the Calculate Nutrients screen

Additional Context
- Sort Number in Excel sheet may not be accurate

**Comment by fergmac** [comment]
The first row in the excel sheet is already in the database so I will skip that row.

![Screenshot 2024-03-04 at 10 35 46 AM](https://github.com/bcgov/agri-nmp/assets/20193291/118293b8-9beb-44e3-bfc4-17d3b897f99a)

![Screenshot 2024-03-04 at 11 45 27 AM](https://github.com/bcgov/agri-nmp/assets/20193291/7e7f5f69-19f5-46da-8ed5-c9140cf0b4d1)

**Comment by joandrews** [comment]
Complete
