### ISSUE TITLE
Crop Details - prunings update incorrectly.

### ISSUE THREAD

**Issue by fergmac** [bcgov/agri-nmp#642]
**Describe the Bug**
After setting the select value for "Where will prunings go?" to "N/A" dynamically based on the value selected for "Will plants be pruned?" being "No" and then making subsequent clicks to the following select elements, the "Where will prunings go?" select option will be unset:
- "# of plants per acre"
- "Distance between plants, distance betweens rows"
- "Calculate"

**Expected Behaviour**
"Where will prunings go?" is updated dynamically and remains set to "N/A"

**Actual Behaviour**
"Where will prunings go?" is reset after subsequent clicks to form selects.

**Implications**
A clear and concise description of any implications.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Make your way through the nutrient calculator flow to: http://localhost:8080/Crops/Crops
2. Click "add crop to test"
3. Select Crop: Blueberry
4. set "Where will prunings go?" to no
5. select value for "Distance between plants, distance betweens rows"

![Image](https://github.com/bcgov/agri-nmp/assets/20193291/9eb92675-bc83-4263-8edf-c9dbcc63e253)

**Comment by fergmac** [comment]
@joandrews 
Due to this application being a server side application with some jQuery to make enhancements we are introducing some odd states when we remove "N/A" from the default select options for "Where will prunings go?".

If this change is providing value we can reassess and see if we can come up with a different solution.

We can add "N/A" back to the defaults which means that it will show as an option in the "Where will prunings go?" on page load:

![Image](https://github.com/bcgov/agri-nmp/assets/20193291/cca7ce35-1938-41ec-9395-266195170081)

Selecting "No" for "Will plants be pruned? will still dynamically update to "N/A" for "Where will prunings go?" and not appear in the list if you select "Yes" for "Will plants be pruned?"
 

![Image](https://github.com/bcgov/agri-nmp/assets/20193291/5c7f49be-0515-47eb-b95e-6ff866d0e587)


![Image](https://github.com/bcgov/agri-nmp/assets/20193291/757a9664-183e-4a9e-8ddf-1918e4a1d3d1)

Otherwise I have rolled back the change in production and we can leave as is.

**Comment by Keegnan** [comment]
We will need SO to decide whether we do work on this ticket or to leave it for now.

**Comment by jakemorr** [comment]
@joandrews could you please take a look at this
