### ISSUE TITLE
Migrate unapplied migrations

### ISSUE THREAD

**Issue by fergmac** [bcgov/agri-nmp#648]
**Describe the task**
Migrations have not been run in the app since we stood it back up. There are some unresolved migrations that exist and need to be reviewed and applied before future NMP work.

- Using a model view to interact with the database. Create a migration and apply the migration to be applied to Dev and Prod environtment

- Go into the app and generate a migration. If they are related to the updated version, go ahead and apply them

- There is a part that could be dependent related.

**Purpose**
If future work requires migrations, we should resolve these unapplied migrations first.

**Acceptance Criteria**
- [ ] No unapplied migrations.

**Additional context**
- Install the EntityFramework command line tool: `dotnet tool install --global dotnet-ef --version 7.0.2`
- List migrations: `dotnet ef migrations list --project ./Server/src/SERVERAPI/SERVERAPI.csproj`

**Comment by acatchpole** [comment]
dotnet Migrations:

There are instructions on how to create and manually run migrations in the NMP confluence page. 

Those instructions are included here below. NOTE: it is (mostly) not necessary to manually run migrations. The app does this on every start up.

When a new migration is created, a model snapshot is used to find all the model changes that do not yet have migration-associated changes. The last migration for NMP was in 2020. A new migration has been created (CatchupModelUpdate) that catches all the model updates that *should* have already had migrations associated with them. 

SNAGS: 
1. In my testing of migrations, the dev db was put into a suboptimal state. the migration history is inaccurate and likely irreconcilable. Currently, it is not possible to run new migrations on the dev db (at least not with the auto-generated migration code). This db will need to be restored to a working state
2. The production database does not have a record of running the last migration, but the results of that migration are present (the 'Depths' table). This might cause errors when rebuilding prod as the migration will run and it will try to add a table that already exists.

**Comment by acatchpole** [comment]
deployed to test with no issues

**Comment by acatchpole** [comment]
deployed to prod
