### ISSUE TITLE
Pre-work: Understanding Calculations behind liquid Fertigation

### ISSUE THREAD

**Issue by Keegnan** [bcgov/agri-nmp#651]
**Objective** 
To understand the calculations that support liquid fertigation application so that it can be incorporated into the overall nutrient balance.

**Additional Context**
- where does this option go on the calculator?
- Intermediate calculation for fertigation (https://bcgov.sharepoint.com/:x:/r/teams/05196-NMP/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7B1019e20f-212c-4a60-affd-5190b341beeb%7D&wdOrigin=TEAMS-MAGLEV.teamsSdk_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1717621883239&web=1)
- Breaking down the excel spreadsheet into the equations that support fertigation
- Proportions don't change through distribution method
- is this a separate feature set that needs to be included for other crops?
- Process of vetting and understanding the calculations and addressing any concerns with the SO

**Acceptance Criteria**
- Document outlining the logic of the calculations, SO provides the calculations and logic steps
- SO to provide test values for calculations

**Comment by Keegnan** [comment]
@joandrews Do you have this information?

**Comment by Keegnan** [comment]
![Image](https://github.com/user-attachments/assets/0807cb12-c8a3-4c1a-b137-1f84a27b8601)

More information on the calculations are detailed in the [Feritigation Calculator Spreadsheet](https://bcgov.sharepoint.com/:x:/r/teams/05196-NMP/Shared%20Documents/NMP/Fertigation%20Calculator%20UX/Fertigation%20Calculator_CALCULATION%20DATA_17June2024.xlsx?d=wd471d96ec21f4721b2b29b7d82767986&csf=1&web=1&e=axG4Nz)

**Comment by Keegnan** [comment]
Take time to account we have everything we need (ie values) to determine the database structure.

**Comment by acatchpole** [comment]
# Fertigation Calculations

Listed below are the expected fields present within the Fertigation Calculator modal. I have given them variable names for ease in referencing them in the equations section. These names are only intended to make reading the equations easier and are not based on any existing variables.

When doing conversions, the default (conversion factor 1) values are the ones that use some combination of US gallons, pounds, and acres. The listed conversion factors are how the different units relate to these base units. The conversionFactor listed always refers to the variable directly preceding it. 

The calculated results for nutrients should always be presented in lb/acre to be consistent with other parts of the nutrient calculator. The calculated volume results could be in whatever unit is provided (but is the result of fields with possibly conflicting units).

The sections that have ```[nitrogen phosphorous potassium]``` are referring to a separate variable for each the nutrient types.

## Input Fields

| Field                                             | Possible Units                                                      | Conversion Factor           |
|---------------------------------------------------|----------------------------------------------------------------------|-----------------------------|
| **Product Rate `<productRate>`**                  | US gallon/ac <br> Imp. gallon/ac <br> L/ac <br> L/ha                 | 1 <br> 0.8328 <br> 3.78541 <br> 9.35396 |
| **Density (provides value but can be edited) `<productDensity>`** | Lb/US gallon <br> Lb/Imp. gallon <br> Kg/L <br> Kg/US gallon        | 1 <br> 0.8328 <br> 8.3509 <br> 2.2037   |
| **Injection Rate `<injectionRate>`**              | US gallon/min <br> Imp. gallon/min <br> L/min                        | 1 <br> 0.8328 <br> 3.78541          |
| **Proposed Number of Fertigations per Season `<numberOfFertigations>`** | number                                                             |                             |
| **Fertilizer Type `<fertilizerType>`**            | Liquid Fertilizer <br> ?Solid Fertilizer? (need to confirm)          |                             |
| **Fertilizer `<fertilizer>`**                     | See list of fertilizers <br> | Unique values for N P2O5 K2O                                        |

## Relevant Data from Earlier in the Calculator

| Field                                             | Possible Units                                                      |
|---------------------------------------------------|----------------------------------------------------------------------|
| **Fertigation Area `<fertigationArea>`**          | acres                                                                |
| **Nutrient Balance `<[nitrogen phosphorous potassium]NutrientBalance>`** | Lb/acre                                                           |

## Calculated Fields

| Field                                             | Possible Units                                                      | Equation                                                                 |
|---------------------------------------------------|----------------------------------------------------------------------|---------------------------------------------------------------------------|
| **Total product volume per fertigation `<volumePerFertigation>`** | US gallon, Imp. gallon, Litre                                         | ```fertigationArea * productRate```                                             |
| **Total product volume per season `<volumePerSeason>`** | US gallon, Imp. gallon, Litre                                         | ```volumePerFertigation * numberOfFertigations```                               |
| **Fertigation time `<fertigationTime>`**          | minutes                                                              | ```volumePerFertigation / injectionRate * conversionFactor?```                  |
| **Applied Nutrients per fertigation `<[nitrogen phosphorous potassium]PerFertigation>`** | Lb/acre | ```(productRate / 100) * productDensity * conversionFactor * fertilizer.[nitrogen phosphorous potassium]``` |
| **Total Applied Nutrients per season `<total[Nitrogen Phosphorous Potassium]PerSeason>`** | Lb/acre                          | ```[nitrogen phosphorous potassium]PerFertigation * numberOfFertigations```     |
| **Still Required this year `<new[Nitrogen Phosphorous Potassium]NutrientBalance>`** | Lb/acre                         | ```[nitrogen phosphorous potassium]NutrientBalance - total[Nitrogen Phosphorous Potassium]PerSeason``` |
