### ISSUE TITLE
On 'Calculate Nutrient' screen add the "add fertigation" button

### ISSUE THREAD

**Issue by Keegnan** [bcgov/agri-nmp#653]
**Describe the task**
on the Calculate Nutrients page of NMP I should be able to select the "Add Fertigation" option along side the add manure and add fertilizer options.

**Purpose**
this is the selection to kick off the fertigation workflow

**Acceptance Criteria**
- [ ] Given i am on NMP when i get to the calculate nutrient button i can select the "Add Fertigation button"
- [ ] Given I have selected the "add fertigation option" a Fertigation Details Modal pops up

**Additional context**
- button is green same as the other options
- Hoping that the modal is a component that we can reuse

**Comment by Keegnan** [comment]
Adding a feature flag that will show up in staging and in dev production.

**Comment by dallascrichmond** [comment]
Added env variable AppSettings__FLAG_FERTIGATION_WORKFLOW to test, dev and prod in openshift. Set test and dev to true so the feature will appear, and prod to false so it won't.
