### ISSUE TITLE
Build Skeleton of Liquid Modal

### ISSUE THREAD

**Issue by jakemorr** [bcgov/agri-nmp#655]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by Keegnan** [comment]
Was a duplicate of a previous ticket.
