### ISSUE TITLE
Apply Calculations to Modal for liquid fertigation

### ISSUE THREAD

**Issue by Keegnan** [bcgov/agri-nmp#658]
**As a** *farmer/consultant* **I want** *fertigation values to be part of the calculation* **So That** * my nutrients are calculated accurately.*

**Additional Context**
- Fields are populated based on the hard coded data available
- On fertigation details modal, after filling in fields clicking calculate, to generate bottom fertigation values 
- is tying into the "calculate" button
- dependent on #656 

**Acceptance Criteria**
- [ ] Given I am on the fertigation details modal and the input fields have been filled, When I click calculate, Then the bottom fertigation values are calculated.
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by acatchpole** [comment]
calculations now ~'work'. Based on nutrient amounts, product rate, and density, as well as their selected units, resultant nutrient amounts are calculated.

We have **NOT** yet verified if these calculations are producing accurate results, but when changing variables, the results change as expected. 

It is very likely that the results are accurate, but it is possible that the *UNITS* the results are in are not what we want. There is some inconsistency in the conversion data in the database (which we use directly or have copied) where sometimes the default value is imp. gallons and other times it is US gallons. It is possible that this is accounted for in the code, but needs to be verified.

While the 'Still Required' fields are being calculated, they are only being calculated off of ONE fertigation event. We need to make the result take into account the number of fertigation events.

Total Product Volumes are also not being calculated. This is not a result for the fertilizer modal, so we will need to create the functions to calculate these values.

The 'Fertigation Time' calculation has also **NOT** been implemented. That remains TODO.
