### ISSUE TITLE
Build Solid Fertigation Component

### ISSUE THREAD

**Issue by Keegnan** [bcgov/agri-nmp#664]
**Describe the task**
Utilizing the modals we have made with liquid fertigation and adding solid fertigation components. Components to remove/add:

Removing:
- product rate
- density
- product volume
- total product volume

Adding:
- tank volume *
- solubility in water *
- amount to dissolve
- action
- nutrient concentrations

**Purpose**
Give use the the ability to add solid fertigation to their fertigation calculation

**Acceptance Criteria**
- All of the fields for solid fertigation are present when selecting a solid fertilizer 

**Additional context**
- Highlights the main difference between liquid and solid
- Changes what fields are available when either liquid or solid is selected
- Should behave similarly to the final version of liquid fertigation
- When a user selects a solid fertilizer and provided the right information, a solid fertilizer is added to the nutrient balance calculation appropriately

**Comment by dallascrichmond** [comment]
![Image](https://github.com/user-attachments/assets/ea4a0bde-f1f3-44f0-8ebf-05fe0f725cde)
