### ISSUE TITLE
[Fertigation] Fix the date selector

### ISSUE THREAD

**Issue by acatchpole** [bcgov/agri-nmp#685]
**Describe the task**
- date selection does not persist
- clicking on the ‘mm-dd-yyyy’ only brings up a month select, not date
- you have to click on the calendar icon to actually bring up the date picker

**Purpose**
The reason why this task is needed and/or what value it adds.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by PaulGarewal** [comment]
Completed in #658
