### ISSUE TITLE
[Fertigation] Populate the density field when a fertilizer is selected

### ISSUE THREAD

**Issue by acatchpole** [bcgov/agri-nmp#686]
**Describe the task**
A clear and concise description of what the task is.

**Purpose**
The reason why this task is needed and/or what value it adds.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by PaulGarewal** [comment]
Completed in #658
