### ISSUE TITLE
Prep for New NMP development

### ISSUE THREAD

**Issue by Keegnan** [bcgov/agri-nmp#688]
**Problem Description** 
**we plan on incrementally replacing the NMP Application with a Mobile First Progressive Web App, this development was started by the Quackstack capstone team. we need to investigate what the steps are to be ready to begin expanding on what they have built while being able to deploy to a production environment

**Solution Needs**
- Better Berries Cloned to new NMP Repo
- New NMP Openshift Space requested
- investigation in to remaining work on QSOS Pipeline
- Determine Database choice for New NMP
- Review Outstanding Betterberries tickets and evaluate if they should be brought over to the new repo/susteam board for future work
- Create Tickets for any of the above's outstanding work

**Outcome**
we are prepared to start work on NewNMP next sprint.

**Additional Context**
- the App currently deploys to a Dev/Demo environment
- currently BetterBerries has no DB, or it has a DB that is unused, as the calculations and data selection is all stored in the FE.
- we do not want to alter the Better Berries Repo in any way as it is used for the Capstone teams portfolio's
- the incremental plan would be each of these big increments would be broken down into tmuch smaller individual increments with a focus on frequent deployment of new modules/workflows:
                      - to clone Berries, and push to production
                      - Build DB and enhance Berries to use it
                      - build out Vegetable Module/workflow (Including Fertigation)
                      - Add Animals workflow

**Comment by dallascrichmond** [comment]
A new NPM OpenShift space has been requested in the BC Platform ServicesProduct Registry.

**Comment by dallascrichmond** [comment]
Created new Repo from QuickStart-Openshift template: https://github.com/bcgov/nmp
