### ISSUE TITLE
Change Headings, Match Units, Rounding Totals, and Action Wording Change

### ISSUE THREAD

**Issue by Keegnan** [bcgov/agri-nmp#703]
**Describe the task**
A couple UI changes requested:
- [x] Change the headings for 'Fertigation Details - Add' page
![Image](https://github.com/user-attachments/assets/05031767-9739-4cf2-a4d2-29994b24f13e)

- [x] Match 'Total Product Volume per Fertigation' and 'Total Product Volume for Growing Season' to the unit the user selects for product rate ![Image](https://github.com/user-attachments/assets/7db1db67-55dc-44c4-8c83-40f3abd8c20f)

- [x] Round Volumes to **One** decimal place, time to the nearest minute (no decimals)
![Image](https://github.com/user-attachments/assets/b4febeab-d76c-4517-a041-ba2fcf212a67)

- [x] Headers for N, P2O5, and K2O need to be aligned and the icons in 'Still Required This Year' should go beside the number totals
![Image](https://github.com/user-attachments/assets/b6156672-3e6c-4c14-be48-8b4cdee9d2fb)

- [x] Change 'Action' header for both Dry Fertilizer and Dry Fertilizer (Custom) to 'Solubility Assessment'
- [x] Change output text from 'Good' to 'Soluble' and keep the green checkmark
![Image](https://github.com/user-attachments/assets/7ebddde9-60a3-49c8-b508-cc9ac3a1c178)

**Additional context**
- See sharepoint slides for more info (UI Edit 1-3 & 11)
- https://bcgov.sharepoint.com/:p:/r/teams/05196-NMP/Shared%20Documents/NMP/Fertigation%20TEST.pptx?d=w9cda866d40a44e1997da34ed621d775c&csf=1&web=1&e=8G8nFS
-

**Comment by joandrews** [comment]
@lunamoonmoon For your fertigation time heading questions, the header should be **Fertigation time** and the text under it should be X minutes. In fact, can all of the headers and subtext on that row (Total Product Volume per Fertigation, Total Product Volume for Growing Season) function the same way?
