### ISSUE TITLE
Adding information icons to certain headers and changing  the tool tip text

### ISSUE THREAD

**Issue by Keegnan** [bcgov/agri-nmp#705]
**Describe the task**
A couple of UI & UX changes to be made in NMP:

- [x] Add information Icon after 'Injection Rate' heading. When clicked, it should read: " Enter the rate in which your fertigation equipment applies fertilizer, not its overall output rate."
- [x] Add information icon after 'Application Rate' (formerly Production Rate). When clicked, it should read: "The rate of fertilizer  to be applied, not the overall output rate of your application system."
- [x] Add information icon after 'Time Per Application' (formerly Fertigation Time). When clicked, it should read: "The amount of time required to apply fertilizer at the input fertilizer application rate, based on the injection rate entered above."
- [ ] Add information icon after 'Tank Volume' if Dry Fertilizer or Dry Fertilizer (Custom) is selected
![Image](https://github.com/user-attachments/assets/e2940b76-14bd-4c1d-8150-7d8b8c6dd54f)

**Additional context**
-  Refer to the Fertigation TEST slides for more information
- https://bcgov.sharepoint.com/:p:/r/teams/05196-NMP/Shared%20Documents/NMP/Fertigation%20TEST.pptx?d=w9cda866d40a44e1997da34ed621d775c&csf=1&web=1&e=OMlrFr

**Comment by lunamoonmoon** [comment]
For "Can you add an information icon after Tank Volume if Dry Fertilizer or Dry Fertilizer (Custom) is selected?" What should the text be once clicked?

**Comment by jakemorr** [comment]
@joandrews can you please provide the text for this as discussed yesterday in our demo?
