### ISSUE TITLE
Fix Solid Fertigation Calculation

### ISSUE THREAD

**Issue by Keegnan** [bcgov/agri-nmp#706]
**Describe the task**
The Fertigation calculation is not functioning correctly,. It will need to be reviewed to insure that the calculations from the Fertigation math spreadsheet is correct.

**Acceptance Criteria**
- [ ] Review calculations from spreadsheet
- [ ] Crosscheck with NMP app to make sure the calculation is same as spreadsheet
- [ ] Make corrections

**Additional context**
- The fertigation should be reviewed in the SOLID tab of the spreadsheet
- [https://bcgov.sharepoint.com/:x:/r/teams/05196-NMP/Shared%20Documents/NMP/Fertigation%20math.xlsx?d=w6a784fb240b84b76aa6bcdd0db18ca3f&csf=1&web=1&e=Gfdg96](url)
-  ![Image](https://github.com/user-attachments/assets/37c7d4af-6cb5-4c7b-91b9-34c048899201)

**Comment by lunamoonmoon** [comment]
[fertigation math](https://bcgov.sharepoint.com/:x:/r/teams/05196-NMP/Shared%20Documents/NMP/Fertigation%20math.xlsx?d=w6a784fb240b84b76aa6bcdd0db18ca3f&csf=1&web=1&e=MbWPRX)
