### ISSUE TITLE
Change units for Nutrient Concentration in Stock Solution

### ISSUE THREAD

**Issue by Keegnan** [bcgov/agri-nmp#707]
**Describe the task**
The Nutrient Concentration in Stock Solution is currently lb/imperial gallon and should be changed to lb/US gallon. The units slected by the user should match product rate.

**Additional context**
- Issue for both "Dry Fertilizer" and "Dry Custom Fertilizer" 
- The correct units can be seen on the SOLID tab in the Fertigation Math Spreadsheet [https://bcgov.sharepoint.com/:x:/r/teams/05196-NMP/Shared%20Documents/NMP/Fertigation%20math.xlsx?d=w6a784fb240b84b76aa6bcdd0db18ca3f&csf=1&web=1&e=Zks2xR](url)
- ![Image](https://github.com/user-attachments/assets/f98b982b-6459-403b-bf9d-19712e09172e)
- ![Image](https://github.com/user-attachments/assets/5fc233d9-43cb-474f-8b69-cae757915690)

**Comment by lunamoonmoon** [comment]
PR 701/ticket 703 - https://github.com/bcgov/agri-nmp/pull/710 already addressed matching units selected by the user in application rate (formely product rate) to total product volume. Please let me know if further fixes are required :)
![Image](https://github.com/user-attachments/assets/9d4f9006-8790-44a1-bbe2-d7001af7a2a1)
