### ISSUE TITLE
.Net version

### ISSUE THREAD

**Issue by cvarjao** [bcgov/agri-nmp#72]
There seems to be some conflict regards which version of .Net is actually being used.
- [.NET Core version 2 Preview (3)](https://github.com/bcgov/agri-nmp/blob/master/Readme.md)
- [ASP.NET Core 1.1 API Server](https://github.com/bcgov/agri-nmp/blob/master/Server/README.md)

**Comment by swcurran** [comment]
Based on the data in the s2i folder, it appears to me that the project is using .NET Core 2.0.

https://github.com/bcgov/agri-nmp/blob/master/.s2i/bin/assemble

@GeorgeWalker - can you confirm that?

@cvarjao - where are the references to 1.1 that need to changed?

**Comment by GeorgeWalker** [comment]
Yes, Agri-NMP uses Dotnet Core 2.0 as the deployment environment.

**Comment by cvarjao** [comment]
I've linked to the 2 readmes I've found, in the description.

**Comment by swcurran** [comment]
Reference changed in the second readme. I don't know how to check if "Preview 3" is still being used, so left that reference as is.
